from django.db import IntegrityError
from django.test import TestCase

from apps.common.test_factories import make_league, make_standing, make_team
from apps.leagues.models import League, Source


class LeagueModelTests(TestCase):
    def test_slug_autogenerated_from_name(self):
        league = make_league(name="La Liga", external_id="PD")
        self.assertEqual(league.slug, "la-liga")

    def test_explicit_slug_preserved(self):
        league = League.objects.create(
            name="Serie A",
            slug="serie-a-it",
            country="Italy",
            source=Source.FOOTBALL_DATA,
            external_id="SA",
        )
        self.assertEqual(league.slug, "serie-a-it")

    def test_source_external_id_unique(self):
        make_league(external_id="PL")
        with self.assertRaises(IntegrityError):
            make_league(external_id="PL", name="Dup")


class StandingModelTests(TestCase):
    def test_standing_uniqueness_per_league_team_season(self):
        league = make_league()
        team = make_team(league)
        make_standing(league, team)
        with self.assertRaises(IntegrityError):
            make_standing(league, team, position=2)
