# Generated by Django 5.0.6 on 2026-06-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_player_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
