# Generated by Django 4.2.30 on 2026-06-27 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matchday', models.PositiveIntegerField(blank=True, null=True)),
                ('kickoff', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=12)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='leagues.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='leagues.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.league')),
            ],
            options={
                'ordering': ['kickoff'],
            },
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_possession', models.FloatField(blank=True, null=True)),
                ('away_possession', models.FloatField(blank=True, null=True)),
                ('home_shots', models.PositiveIntegerField(blank=True, null=True)),
                ('away_shots', models.PositiveIntegerField(blank=True, null=True)),
                ('home_shots_on_target', models.PositiveIntegerField(blank=True, null=True)),
                ('away_shots_on_target', models.PositiveIntegerField(blank=True, null=True)),
                ('home_corners', models.PositiveIntegerField(blank=True, null=True)),
                ('away_corners', models.PositiveIntegerField(blank=True, null=True)),
                ('home_fouls', models.PositiveIntegerField(blank=True, null=True)),
                ('away_fouls', models.PositiveIntegerField(blank=True, null=True)),
                ('home_yellow_cards', models.PositiveIntegerField(blank=True, null=True)),
                ('away_yellow_cards', models.PositiveIntegerField(blank=True, null=True)),
                ('home_red_cards', models.PositiveIntegerField(blank=True, null=True)),
                ('away_red_cards', models.PositiveIntegerField(blank=True, null=True)),
                ('home_xg', models.FloatField(blank=True, null=True)),
                ('away_xg', models.FloatField(blank=True, null=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='matches.match')),
            ],
            options={
                'verbose_name_plural': 'Match stats',
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minute', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('GOAL', 'Goal'), ('YELLOW', 'Yellow card'), ('RED', 'Red card'), ('SUBSTITUTION', 'Substitution'), ('VAR', 'VAR')], max_length=16)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='leagues.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='leagues.team')),
            ],
            options={
                'ordering': ['match', 'minute'],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='matches_mat_status_a896a5_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['kickoff'], name='matches_mat_kickoff_81ae02_idx'),
        ),
    ]
