# Generated by Django 5.0.6 on 2026-06-27 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_odds', models.FloatField(blank=True, null=True)),
                ('draw_odds', models.FloatField(blank=True, null=True)),
                ('away_odds', models.FloatField(blank=True, null=True)),
                ('over25_odds', models.FloatField(blank=True, null=True)),
                ('under25_odds', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='football-data.co.uk', max_length=40)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='matches.match')),
            ],
            options={
                'verbose_name_plural': 'Match odds',
            },
        ),
    ]
