# Generated by Django 5.0.6 on 2026-06-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_player_nickname'),
        ('matches', '0002_matchodds'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_manager',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='match',
            name='home_manager',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='assist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_events', to='leagues.player'),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='type',
            field=models.CharField(choices=[('GOAL', 'Goal'), ('OWN_GOAL', 'Own goal'), ('YELLOW', 'Yellow card'), ('RED', 'Red card'), ('SUBSTITUTION', 'Substitution'), ('VAR', 'VAR')], max_length=16),
        ),
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shirt_number', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=60)),
                ('is_starter', models.BooleanField(default=False)),
                ('subbed_on_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('subbed_off_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='leagues.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='leagues.team')),
            ],
            options={
                'ordering': ['-is_starter', 'shirt_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='matchlineup',
            constraint=models.UniqueConstraint(fields=('match', 'player'), name='uniq_match_player_lineup'),
        ),
    ]
