# Generated by Django 5.0.6 on 2026-06-29 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_coach'),
        ('matches', '0003_match_away_manager_match_home_manager_match_referee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_manager',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_manager',
        ),
        migrations.AddField(
            model_name='match',
            name='away_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='leagues.coach'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='leagues.coach'),
        ),
        # referee/stadium were CharFields; drop the text columns and re-add as
        # FKs (the values are re-derivable from Match.raw_data via backfill).
        migrations.RemoveField(model_name='match', name='referee'),
        migrations.RemoveField(model_name='match', name='stadium'),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.stadium'),
        ),
    ]
